# Generated by Django 4.1.7 on 2024-01-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS2Ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_viewers',
            field=models.IntegerField(null=True),
        ),
    ]
