# Generated by Django 4.1.7 on 2024-01-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS2Ranking', '0002_match_live_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
