# Generated by Django 4.1.7 on 2024-01-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS2Ranking', '0003_alter_player_current_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CS2Ranking.team'),
        ),
    ]
