version: "3.10"

services:
  backend:
    container_name: CS2Ranking
    build:
      context: .
    volumes:
      - ./app:/djangoProject
    ports:
      - "8000:8000"
    restart: always
#  user:
#    container_name: user
#    build:
#      dockerfile: Dockerfile
#      context: ./backend
#    volumes:
#      - ./backend:/backend-dir
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    command:
#      - /bin/bash
#      - -c
#      - |
#        python manage.py makemigrations &&
#        python manage.py migrate &&
#        python manage.py loaddata fixtures/test_data.yaml &&
#        python manage.py test &&
#        python manage.py runserver 0.0.0.0:8000
#    restart: always